image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: aw2QIdli8r9A4eoDn1Edhg==
  DOCKER_PASS:
    secure: 2pScLOEeK1wG1ERXzWeGSw==

install:
  - choco install gitversion.portable -pre -y
  - docker version

before_build:
- ps: gitversion /l console /output buildserver
#- cmd: msbuild %path_to_sln% /t:restore /p:PackageVersion=%GitVersion_FullSemVer%

build_script:
  - ps: .\build.ps1
#- docker build ./IISDev -t me/myfavoriteapp .

# test_script:
#   - docker run me/myfavoriteapp

deploy_script:
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  #- docker push me/myfavoriteapp